### ISSUE TITLE
E14

### ISSUE THREAD

**Issue by boscorelly** [deennoo/domoticz-Xiaomi-Led-Lamp#2]
Hi,

Is it working with the e14 bulb ?

**Comment by deennoo** [comment]
As i don't have it, i don't know.

Looks @ miio lib, and MyAir.py files and adapt it

**Comment by boscorelly** [comment]
the bulbs you support are wifi or zigbee ?

**Comment by deennoo** [comment]
only wifi, for zigbee i'm using Zigate 

https://github.com/sasu-drooz/Domoticz-Zigate

with ikea bulb : just the most advanced zigbee dev who allow the most event as possible

**Comment by SamaelRanger** [comment]
This plugin supports Philips Zhirui Bulb (https://item.mi.com/1172100033.html)
@boscorelly, do you ask about Philips Zhirui Candle Bulb (https://item.mi.com/1180500002.html)? This kind of lamps is supported by phyton-miio library, so I (or you) can easily adapt this plugin to support E14 lamps.

**Comment by boscorelly** [comment]
hi,

i am asking for zigbee ikea bulbs :)

**Comment by SamaelRanger** [comment]
Ah.. Sorry, you better look into
https://github.com/moroen/IKEA-Tradfri-plugin 
https://www.domoticz.com/wiki/Ikea_Tradfri_Gateway
https://www.domoticz.com/forum/viewtopic.php?f=65&t=17312

**Comment by SamaelRanger** [comment]
Close the issue as it related to other product.

**Comment by deennoo** [comment]
For E14 zigbee from Ikea : Zigate is your best tool : https://www.domoticz.com/wiki/Zigate

This Drive Ikea bulb better than Ikea gateway
